### ISSUE TITLE
Error: This project does not contain a lockfile.

### ISSUE THREAD

**Issue by lyaqing** [chinese-quartet/quartet-rseqc-report#9]
Errors when building the environment and compile the quartet-rseqc-report:

cp -R resources/* .env/
export R_PROFILE_USER=.env/Rprofile && Rscript -e 'renv::install("./exp2qcdt");'
Error: This project does not contain a lockfile.
Have you called `snapshot()` yet?
Traceback (most recent calls last):
5: renv::restore()
4: lockfile %||% renv_lockfile_load(project = project, strict = TRUE)
3: renv_lockfile_load(project = project, strict = TRUE)
2: abort(c("This project does not contain a lockfile.", i = "Have you called `snapshot()` yet?"))
1: stop(fallback)
Execution halted
make: *** [Makefile:22: install-exp2qcdt] Error 1

**Comment by yjcyxky** [comment]
Strongly recommend to use docker instead of compiling the tool from the source code.

https://github.com/chinese-quartet/quartet-rseqc-report#for-users-recommended
